AWSTemplateFormatVersion: '2010-09-09'
Description: A basic CloudFormation template to create an S3 bucket.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: iitc-test-cloud-formation
      Tags:
        - Key: Environment
          Value: Development
        - Key: Project
          Value: MyBasicProject