persistence:
  enabled: true
  storageClass: "jenkins-ebs-sc"
  accessMode: "ReadWriteOnce"
  size: "8Gi"

controller:
  admin:
    password: "admin123"
  
  resources:
    requests:
      cpu: "50m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1Gi"
  
  # Jenkins Configuration as Code
  JCasC:
    defaultConfig: true
    configScripts:
      jenkins-config: |
        jenkins:
          mode: NORMAL
          numExecutors: 0
          clouds:
          - kubernetes:
              name: "kubernetes"
              serverUrl: "https://kubernetes.default"
              namespace: "jenkins"
              jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
              jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
