apiVersion: v1
kind: Pod
metadata:
  name: test-custom-nodepool
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  tolerations:
  - key: "custom-workload"
    value: "true"
    effect: "NoSchedule"
  nodeSelector:
    nodepool-type: "custom"
  restartPolicy: Never
