apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-secrets
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager-cluster
    kind: ClusterSecretStore
  target:
    name: jenkins-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github-username: "ronhadad22@gmail.com"
        github-password: "{{ .githubToken }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      key: jenkins/admin
      property: password
  - secretKey: githubToken
    remoteRef:
      key: github-secret
      property: token
