jenkins:
  systemMessage: "Jenkins configured automatically by JCasC with ECR access"
  
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
      
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Jenkins Admin"
        password: "${JENKINS_ADMIN_PASSWORD:-admin123}"

  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
      jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
      name: "kubernetes"
      namespace: "jenkins"
      serverUrl: "https://kubernetes.default"
      templates:
      # Default JNLP agent
      - containers:
        - args: "^${computer.jnlpmac} ^${computer.name}"
          envVars:
          - envVar:
              key: "JENKINS_URL"
              value: "http://jenkins.jenkins.svc.cluster.local:8080/"
          image: "jenkins/inbound-agent:3345.v03dee9b_f88fc-6"
          name: "jnlp"
          resourceLimitCpu: "512m"
          resourceLimitMemory: "512Mi"
          resourceRequestCpu: "512m"
          resourceRequestMemory: "512Mi"
          workingDir: "/home/jenkins/agent"
        label: "jenkins-agent"
        name: "default"
        namespace: "jenkins"
        nodeUsageMode: "NORMAL"
        podRetention: "never"
        serviceAccount: "default"
        slaveConnectTimeout: 100
        
      # Docker + ECR agent with IRSA
      - containers:
        - name: "jnlp"
          image: "jenkins/inbound-agent:3345.v03dee9b_f88fc-6"
          args: "^${computer.jnlpmac} ^${computer.name}"
          resourceRequestCpu: "100m"
          resourceRequestMemory: "256Mi"
          resourceLimitCpu: "500m"
          resourceLimitMemory: "512Mi"
        - name: "docker"
          image: "docker:24-dind"
          privileged: true
          envVars:
          - envVar:
              key: "DOCKER_TLS_CERTDIR"
              value: ""
          volumeMounts:
          - mountPath: "/var/run/docker.sock"
            name: "docker-sock"
          resourceRequestCpu: "500m"
          resourceRequestMemory: "512Mi"
          resourceLimitCpu: "1"
          resourceLimitMemory: "2Gi"
        - name: "aws-cli"
          image: "amazon/aws-cli:latest"
          command: "cat"
          ttyEnabled: true
          envVars:
          - envVar:
              key: "AWS_DEFAULT_REGION"
              value: "us-east-1"
          resourceRequestCpu: "100m"
          resourceRequestMemory: "256Mi"
          resourceLimitCpu: "500m"
          resourceLimitMemory: "512Mi"
        volumes:
        - hostPathVolume:
            hostPath: "/var/run/docker.sock"
            mountPath: "/var/run/docker.sock"
        label: "docker ecr"
        name: "docker-ecr-agent"
        namespace: "jenkins"
        nodeUsageMode: "EXCLUSIVE"
        podRetention: "never"
        serviceAccount: "jenkins-agent"  # IRSA service account
        slaveConnectTimeout: 100
        yaml: |
          apiVersion: v1
          kind: Pod
          spec:
            serviceAccountName: jenkins-agent

  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: true
      
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 0
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  
  remotingSecurity:
    enabled: true
    
  markupFormatter: "plainText"
  
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"

# Jobs configuration
jobs:
  - script: |
      pipelineJob('ecr-build-sample') {
        description('Sample pipeline to build and push to ECR')
        definition {
          cps {
            script('''
              pipeline {
                agent { label 'docker ecr' }
                environment {
                  ECR_REGISTRY = "950555670656.dkr.ecr.us-east-1.amazonaws.com"
                  IMAGE_REPO = "sample-app"
                  IMAGE_TAG = "${BUILD_NUMBER}"
                  AWS_DEFAULT_REGION = "us-east-1"
                }
                stages {
                  stage('Build') {
                    steps {
                      container('docker') {
                        sh '''
                          echo "FROM alpine:latest" > Dockerfile
                          echo "RUN echo 'Hello from Jenkins Build #${BUILD_NUMBER}'" >> Dockerfile
                          docker build -t ${IMAGE_REPO}:${IMAGE_TAG} .
                        '''
                      }
                    }
                  }
                  stage('Push to ECR') {
                    steps {
                      container('aws-cli') {
                        sh 'aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}'
                      }
                      container('docker') {
                        sh '''
                          docker tag ${IMAGE_REPO}:${IMAGE_TAG} ${ECR_REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}
                          docker tag ${IMAGE_REPO}:${IMAGE_TAG} ${ECR_REGISTRY}/${IMAGE_REPO}:latest
                          docker push ${ECR_REGISTRY}/${IMAGE_REPO}:${IMAGE_TAG}
                          docker push ${ECR_REGISTRY}/${IMAGE_REPO}:latest
                        '''
                      }
                    }
                  }
                }
                post {
                  always {
                    echo "Build completed. Image pushed to ECR."
                  }
                }
              }
            ''')
            sandbox()
          }
        }
      }

# Security configuration
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  scriptApproval:
    forceSandbox: false

# Global configuration
unclassified:
  location:
    adminAddress: "admin@company.com"
    url: "http://jenkins.jenkins.svc.cluster.local:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false

# Tool configuration
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
