apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jenkins-ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3    # You can use gp2 or gp3
  fsType: ext4